spring.application.name=support-ticket-classifier-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/support_classifier
spring.datasource.username=postgres
spring.datasource.password=Ss190488!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true